#!/usr/bin/php
<?php
ini_set('memory_limit', '16M');

use TodoApp\Application;

require "vendor/autoload.php";

// TODO find good way for helpers
require "src/helper.php";

$app = Application::init();
for ($i=0; $i < 100; $i++) { 
    $app->addTodo("sdfsdf$i");
}

foreach ($app->todoList() as $value) {
    echo $value->name() . "\n";
}

for ($i=0; $i < 50; $i++) { 
    $app->removeTodo(100-$i);
}

echo "------------\n";

$app->removeTodo(0);

foreach ($app->todoList() as $value) {
    echo $value->name() . "\n";
}

echo "------------\n";
$app->removeTodo(0);

foreach ($app->todoList() as $value) {
    echo $value->name() . "\n";
}
echo "------------\n";

$app->removeTodo(0);

foreach ($app->todoList() as $value) {
    echo $value->name() . "\n";
}

echo "------------\n";