#!/usr/bin/php
<?php
ini_set('memory_limit', '16M');

use TodoApp\Application;

require "vendor/autoload.php";

$app = Application::init();
for ($i=0; $i < 100; $i++) { 
    $app->addTodo("sdfsdf$i");
}

foreach ($app->todoList() as $value) {
    echo $value->name() . "\n";
}

for ($i=0; $i < 50; $i++) { 
    $app->removeTodo(100-$i);
}

dd($app->todoList());
